; Generated by hasc prototype

    SECTION test,data
    cnop 0,4
value:
    dc.l 42

    SECTION feature_test,code
    cnop 0,4

main:
    ; local x: byte at -2(a4)
    ; local y: word at -4(a4)
    ; local z: int at -8(a4)
    link a6,#-12
    move.l a4,-12(a6)  ; save a4 in frame
    move.l a6,a4  ; save frame pointer in a4
    move.b #10,-2(a4)
    move.w #1000,-4(a4)
    move.l #42,-8(a4)
    move.l -8(a4),d0
    move.l -12(a6),a4  ; restore a4 from frame
    unlk a6
    rts