; Generated by hasc prototype

    SECTION game_bss,bss
    cnop 0,4
bullet: ds.b 100  ; struct size=10, count=10
bullet__size equ 10
bullet__stride equ 10
bullet_x equ bullet+0
bullet_y equ bullet+2
bullet_dir_x equ bullet+4
bullet_dir_y equ bullet+5
bullet_frame equ bullet+6
bullet_active equ bullet+7
bullet_anim_delay equ bullet+8

    SECTION test_code,code
    cnop 0,4

        jsr test_performance
        jsr test_function_param
        rts
    

UpdateBullets_OldWay:
    ; local i: int at -4(a4)
    link a6,#-8
    move.l a4,-8(a6)  ; save a4 in frame
    move.l a6,a4  ; save frame pointer in a4
    move.l #0,-4(a4)
for1:
    move.l -4(a4),d0
    moveq #10,d1
    cmp.l d1,d0
    bgt endfor2
    lea bullet,a0
    move.l -4(a4),d1
    mulu.w #10,d1
    addq.l #7,d1
    clr.l d0
    move.b (a0,d1.l),d0
    cmp.l #1,d0
    bne endif4
    lea bullet,a0
    move.l -4(a4),d1
    mulu.w #10,d1
    clr.l d0
    move.w (a0,d1.l),d0
    lea bullet,a0
    move.l -4(a4),d1
    mulu.w #10,d1
    addq.l #4,d1
    clr.l d2
    move.b (a0,d1.l),d2
    add.l d2,d0
    lea bullet,a0
    move.l -4(a4),d1
    mulu.w #10,d1
    move.w d0,(a0,d1.l)
    lea bullet,a0
    move.l -4(a4),d1
    mulu.w #10,d1
    addq.l #2,d1
    clr.l d0
    move.w (a0,d1.l),d0
    lea bullet,a0
    move.l -4(a4),d1
    mulu.w #10,d1
    addq.l #5,d1
    clr.l d2
    move.b (a0,d1.l),d2
    add.l d2,d0
    lea bullet,a0
    move.l -4(a4),d1
    mulu.w #10,d1
    addq.l #2,d1
    move.w d0,(a0,d1.l)
    lea bullet,a0
    move.l -4(a4),d1
    mulu.w #10,d1
    addq.l #6,d1
    clr.l d0
    move.b (a0,d1.l),d0
    addq.l #1,d0
    andi.l #3,d0
    lea bullet,a0
    move.l -4(a4),d1
    mulu.w #10,d1
    addq.l #6,d1
    move.b d0,(a0,d1.l)
endif4:
forcont3:
    moveq #1,d1
    move.l -4(a4),d0
    add.l d1,d0
    move.l d0,-4(a4)
    bra for1
endfor2:
    move.l -8(a6),a4  ; restore a4 from frame
    unlk a6
    rts

UpdateBullets_NewWay:
    ; local i: int at -4(a4)
    ; local b: bullet* at -8(a4)
    link a6,#-12
    move.l a4,-12(a6)  ; save a4 in frame
    move.l a6,a4  ; save frame pointer in a4
    move.l #0,-4(a4)
for5:
    move.l -4(a4),d0
    moveq #10,d1
    cmp.l d1,d0
    bgt endfor6
    ; b = UnaryOp(op='&', operand=ArrayAccess(name='bullet', indices=[VarRef(name='i')]))
    lea bullet,a0
    move.l -4(a4),d1
    mulu.w #10,d1
    lea (a0,d1.l),a0
    move.l a0,d0
    move.l d0,-8(a4)
    move.l -8(a4),a0
    clr.l d0
    move.b 7(a0),d0
    cmp.l #1,d0
    bne endif8
    move.l -8(a4),a0
    clr.l d0
    move.w (a0),d0
    move.l -8(a4),a0
    clr.l d2
    move.b 4(a0),d2
    add.l d2,d0
    move.l -8(a4),a0
    move.w d0,(a0)
    move.l -8(a4),a0
    clr.l d0
    move.w 2(a0),d0
    move.l -8(a4),a0
    clr.l d2
    move.b 5(a0),d2
    add.l d2,d0
    move.l -8(a4),a0
    move.w d0,2(a0)
    move.l -8(a4),a0
    clr.l d0
    move.b 6(a0),d0
    addq.l #1,d0
    andi.l #3,d0
    move.l -8(a4),a0
    move.b d0,6(a0)
endif8:
forcont7:
    moveq #1,d1
    move.l -4(a4),d0
    add.l d1,d0
    move.l d0,-4(a4)
    bra for5
endfor6:
    move.l -12(a6),a4  ; restore a4 from frame
    unlk a6
    rts

InitBullet:
    ; param b_ptr: bullet* in a0
    ; param start_x: word in d0
    ; param start_y: word in d1
    ; local start_x: word at -4(a4)
    ; local start_y: word at -8(a4)
    link a6,#-12
    move.l d0,-4(a6)  ; save start_x from d0
    move.l d1,-8(a6)  ; save start_y from d1
    move.l a4,-12(a6)  ; save a4 in frame
    move.l a6,a4  ; save frame pointer in a4
    move.w -4(a4),d0
    ext.l d0
    move.l -12(a4),a0
    move.w d0,(a0)
    move.w -8(a4),d0
    ext.l d0
    move.l -12(a4),a0
    move.w d0,2(a0)
    moveq #1,d0
    move.l -12(a4),a0
    move.b d0,4(a0)
    moveq #-1,d0
    move.l -12(a4),a0
    move.b d0,5(a0)
    moveq #0,d0
    move.l -12(a4),a0
    move.b d0,6(a0)
    moveq #1,d0
    move.l -12(a4),a0
    move.b d0,7(a0)
    moveq #6,d0
    move.l -12(a4),a0
    move.b d0,8(a0)
    move.l -12(a6),a4  ; restore a4 from frame
    unlk a6
    rts

test_performance:
    ; local i: int at -4(a4)
    link a6,#-8
    move.l a4,-8(a6)  ; save a4 in frame
    move.l a6,a4  ; save frame pointer in a4
    move.l #0,-4(a4)
for9:
    move.l -4(a4),d0
    moveq #10,d1
    cmp.l d1,d0
    bgt endfor10
    move.l -4(a4),d0
    moveq #10,d2
    ext.l d0  ; normalize to signed 16-bit source semantics
    ext.l d2  ; normalize to signed 16-bit source semantics
    muls.w d2,d0
    lea bullet,a0
    move.l -4(a4),d1
    mulu.w #10,d1
    move.w d0,(a0,d1.l)
    move.l -4(a4),d0
    moveq #20,d2
    ext.l d0  ; normalize to signed 16-bit source semantics
    ext.l d2  ; normalize to signed 16-bit source semantics
    muls.w d2,d0
    lea bullet,a0
    move.l -4(a4),d1
    mulu.w #10,d1
    addq.l #2,d1
    move.w d0,(a0,d1.l)
    moveq #1,d0
    lea bullet,a0
    move.l -4(a4),d1
    mulu.w #10,d1
    addq.l #4,d1
    move.b d0,(a0,d1.l)
    moveq #1,d0
    lea bullet,a0
    move.l -4(a4),d1
    mulu.w #10,d1
    addq.l #5,d1
    move.b d0,(a0,d1.l)
    moveq #0,d0
    lea bullet,a0
    move.l -4(a4),d1
    mulu.w #10,d1
    addq.l #6,d1
    move.b d0,(a0,d1.l)
    moveq #1,d0
    lea bullet,a0
    move.l -4(a4),d1
    mulu.w #10,d1
    addq.l #7,d1
    move.b d0,(a0,d1.l)
forcont11:
    moveq #1,d1
    move.l -4(a4),d0
    add.l d1,d0
    move.l d0,-4(a4)
    bra for9
endfor10:
    jsr UpdateBullets_OldWay
    lea bullet,a0
    moveq #0,d1
    mulu.w #10,d1
    clr.l d0
    move.w (a0,d1.l),d0
    cmp.l #11,d0
    beq endif12
    moveq #-1,d0
    move.l -8(a6),a4  ; restore a4 from frame
    unlk a6
    rts
endif12:
    lea bullet,a0
    moveq #0,d1
    mulu.w #10,d1
    addq.l #2,d1
    clr.l d0
    move.w (a0,d1.l),d0
    cmp.l #1,d0
    beq endif13
    moveq #-2,d0
    move.l -8(a6),a4  ; restore a4 from frame
    unlk a6
    rts
endif13:
    move.l #0,-4(a4)
for14:
    move.l -4(a4),d0
    moveq #10,d1
    cmp.l d1,d0
    bgt endfor15
    move.l -4(a4),d0
    moveq #10,d2
    ext.l d0  ; normalize to signed 16-bit source semantics
    ext.l d2  ; normalize to signed 16-bit source semantics
    muls.w d2,d0
    lea bullet,a0
    move.l -4(a4),d1
    mulu.w #10,d1
    move.w d0,(a0,d1.l)
    move.l -4(a4),d0
    moveq #20,d2
    ext.l d0  ; normalize to signed 16-bit source semantics
    ext.l d2  ; normalize to signed 16-bit source semantics
    muls.w d2,d0
    lea bullet,a0
    move.l -4(a4),d1
    mulu.w #10,d1
    addq.l #2,d1
    move.w d0,(a0,d1.l)
forcont16:
    moveq #1,d1
    move.l -4(a4),d0
    add.l d1,d0
    move.l d0,-4(a4)
    bra for14
endfor15:
    jsr UpdateBullets_NewWay
    lea bullet,a0
    moveq #0,d1
    mulu.w #10,d1
    clr.l d0
    move.w (a0,d1.l),d0
    cmp.l #11,d0
    beq endif17
    moveq #-3,d0
    move.l -8(a6),a4  ; restore a4 from frame
    unlk a6
    rts
endif17:
    lea bullet,a0
    moveq #0,d1
    mulu.w #10,d1
    addq.l #2,d1
    clr.l d0
    move.w (a0,d1.l),d0
    cmp.l #1,d0
    beq endif18
    moveq #-4,d0
    move.l -8(a6),a4  ; restore a4 from frame
    unlk a6
    rts
endif18:
    moveq #0,d0
    move.l -8(a6),a4  ; restore a4 from frame
    unlk a6
    rts

test_function_param:
    ; local p: bullet* at -4(a4)
    link a6,#-8
    move.l a4,-8(a6)  ; save a4 in frame
    move.l a6,a4  ; save frame pointer in a4
    moveq #0,d0
    lea bullet,a0
    moveq #5,d1
    mulu.w #10,d1
    addq.l #7,d1
    move.b d0,(a0,d1.l)
    ; p = UnaryOp(op='&', operand=ArrayAccess(name='bullet', indices=[Number(value=5)]))
    lea bullet,a0
    lea 50(a0),a0
    move.l a0,d0
    move.l d0,-4(a4)
    move.l a0,-(a7)
    move.l d1,-(a7)
    move.l -4(a4),a0
    move.l a0,-(a7)
    move.l #100,-(a7)
    move.l #200,-(a7)
    move.l (a7)+,d1
    move.l (a7)+,d0
    move.l (a7)+,a0
    ; param b_ptr: bullet* in a0
    ; param start_x: word in d0
    ; param start_y: word in d1
    jsr InitBullet
    move.l (a7)+,d1
    move.l (a7)+,a0
    lea bullet,a0
    moveq #5,d1
    mulu.w #10,d1
    clr.l d0
    move.w (a0,d1.l),d0
    cmp.l #100,d0
    beq endif19
    moveq #-1,d0
    move.l -8(a6),a4  ; restore a4 from frame
    unlk a6
    rts
endif19:
    lea bullet,a0
    moveq #5,d1
    mulu.w #10,d1
    addq.l #2,d1
    clr.l d0
    move.w (a0,d1.l),d0
    cmp.l #200,d0
    beq endif20
    moveq #-2,d0
    move.l -8(a6),a4  ; restore a4 from frame
    unlk a6
    rts
endif20:
    lea bullet,a0
    moveq #5,d1
    mulu.w #10,d1
    addq.l #7,d1
    clr.l d0
    move.b (a0,d1.l),d0
    cmp.l #1,d0
    beq endif21
    moveq #-3,d0
    move.l -8(a6),a4  ; restore a4 from frame
    unlk a6
    rts
endif21:
    lea bullet,a0
    moveq #5,d1
    mulu.w #10,d1
    addq.l #4,d1
    clr.l d0
    move.b (a0,d1.l),d0
    cmp.l #1,d0
    beq endif22
    moveq #-4,d0
    move.l -8(a6),a4  ; restore a4 from frame
    unlk a6
    rts
endif22:
    moveq #0,d0
    move.l -8(a6),a4  ; restore a4 from frame
    unlk a6
    rts