; Generated by hasc prototype

    SECTION main,code
    cnop 0,4

        jmp main
    

stack_add:
    ; param a: long at 8(a6)
    ; param b: long at 12(a6)
    ; param c: long at 16(a6)
    link a6,#0
    move.l 8(a6),d0
    move.l 12(a6),d1
    add.l d1,d0
    move.l 16(a6),d1
    add.l d1,d0
    unlk a6
    rts

reg_add:
    ; param a: long in d0
    ; param b: long in d1
    ; local a: long at -4(a4)
    ; local b: long at -8(a4)
    link a6,#-12
    move.l d0,-4(a6)  ; save a from d0
    move.l d1,-8(a6)  ; save b from d1
    move.l a4,-12(a6)  ; save a4 in frame
    move.l a6,a4  ; save frame pointer in a4
    move.l -4(a4),d0
    move.l -8(a4),d1
    add.l d1,d0
    move.l -12(a6),a4  ; restore a4 from frame
    unlk a6
    rts

mixed_func:
    ; param fast: long in d0
    ; param slow1: long at 8(a6)
    ; param slow2: long at 12(a6)
    ; local fast: long at -4(a4)
    link a6,#-8
    move.l d0,-4(a6)  ; save fast from d0
    move.l a4,-8(a6)  ; save a4 in frame
    move.l a6,a4  ; save frame pointer in a4
    move.l -4(a4),d0
    move.l 8(a6),d1
    add.l d1,d0
    move.l 12(a6),d1
    add.l d1,d0
    move.l -8(a6),a4  ; restore a4 from frame
    unlk a6
    rts

main:
    ; local sum1: long at -4(a4)
    ; local sum2: long at -8(a4)
    ; local sum3: long at -12(a4)
    link a6,#-16
    move.l a4,-16(a6)  ; save a4 in frame
    move.l a6,a4  ; save frame pointer in a4
    move.l #30,-(a7)
    move.l #20,-(a7)
    move.l #10,-(a7)
    jsr stack_add
    add.l #12,a7
    move.l d0,-4(a4)
    move.l d1,-(a7)
    move.l #5,-(a7)
    move.l #7,-(a7)
    move.l (a7)+,d1
    move.l (a7)+,d0
    jsr reg_add
    move.l (a7)+,d1
    move.l d0,-8(a4)
    move.l #300,-(a7)
    move.l #200,-(a7)
    move.l #100,-(a7)
    move.l (a7)+,d0
    jsr mixed_func
    add.l #8,a7
    move.l d0,-12(a4)
    move.l -16(a6),a4  ; restore a4 from frame
    unlk a6
    rts