; Generated by hasc prototype

    SECTION test,code
    cnop 0,4

fast_add:
    ; param a: int in d0
    ; param b: int in d1

    add.l d1,d0

    moveq #0,d0
    rts

main:
    link a6,#0
    move.l d1,-(a7)
    move.l #5,-(a7)
    move.l #3,-(a7)
    move.l (a7)+,d1
    move.l (a7)+,d0
    jsr fast_add
    move.l (a7)+,d1
    unlk a6
    rts