; Generated by hasc prototype

    SECTION samples,data
    cnop 0,4
values:
    dc.l 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15

    SECTION main,code
    cnop 0,4

read_value:
    ; param index: int at 8(a6)
    link a6,#0
    lea values,a0
    move.l 8(a6),d1
    lsl.l #2,d1
    move.l (a0,d1.l),d0
    unlk a6
    rts

read_offset_value:
    ; param index: int at 8(a6)
    ; local offset: int at -4(a4)
    link a6,#-8
    move.l a4,-8(a6)  ; save a4 in frame
    move.l a6,a4  ; save frame pointer in a4
    move.l 8(a6),d0
    addq.l #2,d0
    move.l d0,-4(a4)
    lea values,a0
    move.l -4(a4),d1
    lsl.l #2,d1
    move.l (a0,d1.l),d0
    move.l -8(a6),a4  ; restore a4 from frame
    unlk a6
    rts