; Generated by hasc prototype

    SECTION main,code
    cnop 0,4

add:
    ; param a: int at 8(a6)
    ; param b: int at 12(a6)
    link a6,#0
    move.l 8(a6),d0
    move.l 12(a6),d1
    add.l d1,d0
    unlk a6
    rts

add_reg:
    ; param a: int in d0
    ; param b: int in d1
    ; local a: int at -4(a4)
    ; local b: int at -8(a4)
    ; local sum: int at -12(a4)
    link a6,#-16
    move.l d0,-4(a6)  ; save a from d0
    move.l d1,-8(a6)  ; save b from d1
    move.l a4,-16(a6)  ; save a4 in frame
    move.l a6,a4  ; save frame pointer in a4
    move.l -4(a4),d0
    move.l -8(a4),d1
    add.l d1,d0
    move.l d0,-12(a4)
    move.l -16(a6),a4  ; restore a4 from frame
    unlk a6
    rts

add_mixed:
    ; param a: int in d0
    ; param b: int at 8(a6)
    ; local a: int at -4(a4)
    ; local sum: int at -8(a4)
    link a6,#-12
    move.l d0,-4(a6)  ; save a from d0
    move.l a4,-12(a6)  ; save a4 in frame
    move.l a6,a4  ; save frame pointer in a4
    move.l -4(a4),d0
    move.l 8(a6),d1
    add.l d1,d0
    move.l d0,-8(a4)
    move.l -12(a6),a4  ; restore a4 from frame
    unlk a6
    rts

caller:
    ; local x: int at -4(a4)
    ; local y: int at -8(a4)
    ; local r1: int at -12(a4)
    ; local r2: int at -16(a4)
    ; local r3: int at -20(a4)
    link a6,#-24
    move.l a4,-24(a6)  ; save a4 in frame
    move.l a6,a4  ; save frame pointer in a4
    move.l #1,-4(a4)
    move.l #2,-8(a4)
    move.l -8(a4),-(a7)
    move.l -4(a4),-(a7)
    jsr add
    add.l #8,a7
    move.l d0,-12(a4)
    move.l d1,-(a7)
    move.l -4(a4),d0
    move.l d0,-(a7)
    move.l -8(a4),d1
    move.l d1,-(a7)
    move.l (a7)+,d1
    move.l (a7)+,d0
    jsr add_reg
    move.l (a7)+,d1
    move.l d0,-16(a4)
    move.l -8(a4),-(a7)
    move.l -4(a4),d0
    move.l d0,-(a7)
    move.l (a7)+,d0
    jsr add_mixed
    addq.l #4,a7
    move.l d0,-20(a4)
    move.l -12(a4),d0
    move.l -16(a4),d1
    add.l d1,d0
    move.l -20(a4),d1
    add.l d1,d0
    move.l -24(a6),a4  ; restore a4 from frame
    unlk a6
    rts