; Generated by hasc prototype

    SECTION test,code
    cnop 0,4

check_flag:
    ; param enabled: bool at 8(a6)
    link a6,#0
    move.l 8(a6),d0
    andi.l #$FF,d0
    cmp.l #1,d0
    bne endif1
    moveq #1,d0
    unlk a6
    rts
endif1:
    moveq #0,d0
    unlk a6
    rts