; Generated by hasc prototype

    SECTION main,code
    cnop 0,4

main:
    ; local result1: long at -4(a4)
    ; local result2: long at -8(a4)
    link a6,#-12
    move.l a4,-12(a6)  ; save a4 in frame
    move.l a6,a4  ; save frame pointer in a4
    move.l #42,-(a7)
    jsr helper
    addq.l #4,a7
    move.l d0,-4(a4)
    move.l #20,-(a7)
    move.l #10,-(a7)
    jsr compute
    add.l #8,a7
    move.l d0,-8(a4)
    move.l -12(a6),a4  ; restore a4 from frame
    unlk a6
    rts

helper:
    ; param x: long at 8(a6)
    link a6,#0
    move.l 8(a6),d0
    moveq #2,d1
    ext.l d0  ; normalize to signed 16-bit source semantics
    ext.l d1  ; normalize to signed 16-bit source semantics
    muls.w d1,d0
    unlk a6
    rts

compute:
    ; param a: long at 8(a6)
    ; param b: long at 12(a6)
    link a6,#0
    move.l 8(a6),d0
    move.l d0,-(a7)  ; preserve left operand
    move.l 12(a6),d1
    moveq #3,d2
    ext.l d1  ; normalize to signed 16-bit source semantics
    ext.l d2  ; normalize to signed 16-bit source semantics
    muls.w d2,d1
    move.l (a7)+,d0  ; restore left operand
    add.l d1,d0
    unlk a6
    rts