; Generated by hasc prototype

    SECTION test,code
    cnop 0,4

comprehensive_operators:
    ; local x: int at -4(a4)
    ; local y: int at -8(a4)
    ; local result: int at -12(a4)
    ; local i: int at -16(a4)
    link a6,#-20
    move.l a4,-20(a6)  ; save a4 in frame
    move.l a6,a4  ; save frame pointer in a4
    move.l #42,-4(a4)
    move.l #10,-8(a4)
    move.l #0,-12(a4)
    ; x += Number(value=8)
    moveq #8,d1
    move.l -4(a4),d0
    add.l d1,d0
    move.l d0,-4(a4)
    ; y -= Number(value=2)
    moveq #2,d1
    move.l -8(a4),d0
    sub.l d1,d0
    move.l d0,-8(a4)
    ; x *= Number(value=2)
    move.l -4(a4),d0
    moveq #2,d1
    ext.l d0  ; normalize to signed 16-bit source semantics
    ext.l d1  ; normalize to signed 16-bit source semantics
    muls.w d1,d0
    move.l d0,-4(a4)
    ; y &= Number(value=15)
    moveq #15,d1
    move.l -8(a4),d0
    and.l d1,d0
    move.l d0,-8(a4)
    ; y |= Number(value=16)
    moveq #16,d1
    move.l -8(a4),d0
    or.l d1,d0
    move.l d0,-8(a4)
    ; y ^= Number(value=10)
    moveq #10,d1
    move.l -8(a4),d0
    eor.l d1,d0
    move.l d0,-8(a4)
    add.l #1,-4(a4)
    add.l #1,-8(a4)
    ; result = BinOp(op='+', left=VarRef(name='x'), right=VarRef(name='y'))
    move.l -4(a4),d0
    move.l -8(a4),d1
    add.l d1,d0
    move.l d0,-12(a4)
    move.l #0,-16(a4)
while1:
    move.l -16(a4),d0
    cmp.l #5,d0
    bge endwhile2
    ; result += VarRef(name='i')
    move.l -16(a4),d1
    move.l -12(a4),d0
    add.l d1,d0
    move.l d0,-12(a4)
    add.l #1,-16(a4)
    bra while1
endwhile2:
    move.l -12(a4),d0
    move.l -20(a6),a4  ; restore a4 from frame
    unlk a6
    rts