"""`.has` skeleton emitter.

Turns a MetadataManager into a compilable, system-friendly Intuition program
that calls only the `gui_intuition` runtime API documented in
docs/GUI_INTUITION_RUNTIME_SPEC.md.

Regeneration is non-destructive: anything the user writes between
`// USER CODE BEGIN <key>` and `// USER CODE END <key>` in a previously
generated file is carried over into the new one.
"""

from __future__ import annotations

import re
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional

from .model import (
    DEFAULT_IDCMP,
    Control,
    ControlType,
    MetadataManager,
)

_USER_BLOCK_RE = re.compile(
    r"//\s*USER CODE BEGIN\s+(?P<key>\S+)\s*\n(?P<body>.*?)^[ \t]*//\s*USER CODE END\s+(?P=key)",
    re.DOTALL | re.MULTILINE,
)


class HasEmitter:
    """Renders the HAS source for one designed form."""

    def __init__(
        self,
        manager: MetadataManager,
        module_name: str = "gui_form",
        meta_source: str = "<in-memory>",
        user_code: Optional[Dict[str, str]] = None,
    ) -> None:
        self.m = manager
        self.module = re.sub(r"\W", "_", module_name) or "gui_form"
        self.meta_source = _portable_path(meta_source)
        self.user_code = user_code or {}
        self.buttons = manager.by_kind(ControlType.BUTTON)
        self.editboxes = manager.by_kind(ControlType.EDITBOX)
        self.labels = manager.by_kind(ControlType.LABEL)

    # -- public ------------------------------------------------------------
    def render(self) -> str:
        out: List[str] = []
        out += self._header()
        out += self._constants()
        out += self._code_section()
        out += self._data_section()
        out += self._bss_section()
        return "\n".join(out).rstrip() + "\n"

    # -- sections ----------------------------------------------------------
    def _header(self) -> List[str]:
        win = self.m.window
        return [
            "// =============================================================================",
            f"// {self.module}.has - GENERATED BY guicreator",
            f"// Layout source : {self.meta_source}",
            f"// Generated     : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            "//",
            "// System-friendly intuition.library form. Hardware registers are never",
            "// touched; all rendering goes through the window RastPort.",
            "//",
            "// Only the bodies between USER CODE BEGIN/END markers survive regeneration.",
            "//",
            "// Build:",
            f"//   python -m hasc.cli {self.module}.has -o build/{self.module}.s",
            f"//   vasmm68k_mot -Fhunk -I lib/ -o build/{self.module}.o build/{self.module}.s",
            "//   vasmm68k_mot -Fhunk -I lib/ -o build/gui_intuition.o  lib/gui_intuition.s",
            "//   vasmm68k_mot -Fhunk -I lib/ -o build/wbstartup.o      lib/wbstartup.s",
            f"//   vlink -bamigahunk build/{self.module}.o build/gui_intuition.o \\",
            f"//       build/wbstartup.o -o build/{self.module}.exe",
            "// =============================================================================",
            "",
            f"// Window: \"{win.caption}\"  {win.width}x{win.height} at ({win.left},{win.top})",
            "",
        ]

    def _constants(self) -> List[str]:
        win = self.m.window
        lines = [
            "// ---- window geometry (designer canvas, window-relative pixels) ----",
            f"const WIN_X = {win.left};",
            f"const WIN_Y = {win.top};",
            f"const WIN_W = {win.width};",
            f"const WIN_H = {win.height};",
            "",
            "// ---- IDCMP mask and window flags (see docs/GUI_INTUITION_RUNTIME_SPEC.md) ----",
            f"const FORM_IDCMP = ${DEFAULT_IDCMP:08X};",
            f"const FORM_FLAGS = ${win.window_flags():08X};",
            "",
            "// ---- event classes returned by GuiWaitEvent() ----",
            "const GUI_EVT_NONE    = 0;",
            "const GUI_EVT_CLOSE   = 1;",
            "const GUI_EVT_BUTTON  = 2;",
            "const GUI_EVT_PRESS   = 3;",
            "const GUI_EVT_STRING  = 4;",
            "const GUI_EVT_KEY     = 5;",
            "const GUI_EVT_MOUSE   = 6;",
            "const GUI_EVT_REFRESH = 7;",
            "",
            "// ---- widget ActionIDs (mirrored in the .hasmeta layout) ----",
        ]
        if self.m.controls:
            width = max(len(c.id_const) for c in self.m.controls)
            for c in self.m.controls:
                lines.append(f"const {c.id_const:<{width}} = {c.action_id};")
        else:
            lines.append("// (no controls placed)")
        if self.editboxes:
            lines.append("")
            lines.append("// ---- string gadget buffer sizes (maxlen counts the NUL) ----")
            width = max(len(c.maxlen_const) for c in self.editboxes)
            for c in self.editboxes:
                lines.append(f"const {c.maxlen_const:<{width}} = {c.maxlen};")
        lines.append("")
        return lines

    def _externs(self) -> List[str]:
        # Only declare what the emitted code calls: hasc turns every extern into an
        # XREF, and vasm warns (62) about imported symbols that are never referenced.
        lines = [
            "    // ---- Workbench / CLI startup handshake (lib/wbstartup.s) ----",
            "    extern func WBStartup() -> void;",
            "    extern func WBExit() -> void;",
            "",
            "    // ---- gui_intuition runtime (lib/gui_intuition.s) ----",
            "    extern func GuiInit() -> int;",
            "    extern func GuiShutdown() -> void;",
            "    extern func GuiBeginWindow(title: int, x: int, y: int, w: int, h: int,",
            "                               idcmp: int, flags: int) -> int;",
        ]
        if self.labels:
            lines.append("    extern func GuiAddLabel(id: int, x: int, y: int, text: int) -> int;")
        if self.buttons:
            lines.append("    extern func GuiAddButton(id: int, x: int, y: int, w: int, h: int,")
            lines.append("                             caption: int) -> int;")
        if self.editboxes:
            lines.append("    extern func GuiAddEditBox(id: int, x: int, y: int, w: int, h: int,")
            lines.append("                              buf: int, undo: int, maxlen: int) -> int;")
        lines += [
            "    extern func GuiShow() -> int;",
            "    extern func GuiCloseWindow() -> void;",
            "    extern func GuiWaitEvent() -> int;",
            "    extern func GuiGetEventID() -> int;",
            "    extern func GuiGetEventCode() -> int;",
        ]
        if self.editboxes:
            lines.append("    extern func GuiGetEditText(id: int) -> int;")
        lines += [
            "",
            self._user_block("form.externs", 4, "", seed=self._optional_externs()),
            "",
        ]
        return lines

    @staticmethod
    def _optional_externs() -> List[str]:
        return [
            "// Uncomment the rest of the gui_intuition API as your handlers need it.",
            "// extern func GuiGetEventX() -> int;",
            "// extern func GuiGetEventY() -> int;",
            "// extern func GuiSetEditText(id: int, text: int) -> int;",
            "// extern func GuiSetLabelText(id: int, text: int) -> int;",
            "// extern func GuiEnableWidget(id: int, enable: int) -> int;",
            "// extern func GuiActivateEdit(id: int) -> int;",
            "// extern func GuiRedraw() -> void;",
        ]

    def _code_section(self) -> List[str]:
        lines = [f"code {self.module}:", ""]
        lines += self._externs()
        lines += [
            "    public main;",
            "",
            "    // Execution starts at the first emitted instruction, not at main().",
            "    asm {",
            "        jsr WBStartup",
            "        jsr main",
            "        jsr WBExit",
            "        rts",
            "    }",
            "",
        ]
        lines += self._proc_main()
        lines += self._proc_event_loop()
        if self.buttons:
            lines += self._proc_on_button()
        if self.editboxes:
            lines += self._proc_on_string()
        lines += self._proc_on_key()
        lines += self._proc_on_close()
        return lines

    def _proc_main(self) -> List[str]:
        lines = [
            "    // -------------------------------------------------------------------",
            "    // main - build the form, open it, run the event loop, clean up.",
            "    // Returns 0 on a normal exit, -1 if the GUI could not be created.",
            "    // -------------------------------------------------------------------",
            "    proc main() -> int {",
            "        var status: int;",
            "        var win: int;",
            "",
            "        status = GuiInit();",
            "        if (status != 0) {",
            "            return -1;",
            "        }",
            "",
            "        status = GuiBeginWindow(&win_title, WIN_X, WIN_Y, WIN_W, WIN_H,",
            "                                FORM_IDCMP, FORM_FLAGS);",
            "        if (status != 0) {",
            "            call GuiShutdown();",
            "            return -1;",
            "        }",
            "",
            "        // Widgets are added BEFORE the window opens: the runtime links them",
            "        // into nw_FirstGadget, so OpenWindow renders them in one pass.",
            "        // List order is also the TAB cycle order.",
        ]
        for c in self.m.controls:
            lines.append("        " + self._add_call(c))
        lines += [
            "",
            "        win = GuiShow();",
            "        if (win == 0) {",
            "            call GuiShutdown();",
            "            return -1;",
            "        }",
            "",
            self._user_block("main.after_show", 8, "custom initialisation once the window is up"),
            "",
            "        call event_loop();",
            "",
            "        call GuiCloseWindow();",
            "        call GuiShutdown();",
            "        return 0;",
            "    }",
            "",
        ]
        return lines

    def _add_call(self, c: Control) -> str:
        if c.kind is ControlType.LABEL:
            return f"call GuiAddLabel({c.id_const}, {c.x}, {c.y}, &{c.text_symbol});"
        if c.kind is ControlType.BUTTON:
            return (
                f"call GuiAddButton({c.id_const}, {c.x}, {c.y}, {c.w}, {c.h}, "
                f"&{c.text_symbol});"
            )
        return (
            f"call GuiAddEditBox({c.id_const}, {c.x}, {c.y}, {c.w}, {c.h}, "
            f"&{c.buffer_symbol}, &{c.undo_symbol}, {c.maxlen_const});"
        )

    def _proc_event_loop(self) -> List[str]:
        lines = [
            "    // -------------------------------------------------------------------",
            "    // event_loop - blocks in GuiWaitEvent() until the window is closed.",
            "    // GuiWaitEvent() replies every IntuiMessage before returning, so no",
            "    // message memory is ever read after ReplyMsg().",
            "    // -------------------------------------------------------------------",
            "    proc event_loop() -> int {",
            "        var evt: int;",
            "        var id: int;",
            "        var running: int = 1;",
            "",
            "        while (running != 0) {",
            "            evt = GuiWaitEvent();",
            "            id = GuiGetEventID();",
            "",
            "            if (evt == GUI_EVT_CLOSE) {",
            "                running = on_close();",
            "            }",
        ]
        if self.buttons:
            lines += [
                "",
                "            if (evt == GUI_EVT_BUTTON) {",
                "                running = on_button(id);",
                "            }",
            ]
        if self.editboxes:
            lines += [
                "",
                "            if (evt == GUI_EVT_STRING) {",
                "                running = on_string(id);",
                "            }",
            ]
        lines += [
            "",
            "            if (evt == GUI_EVT_KEY) {",
            "                running = on_key(GuiGetEventCode());",
            "            }",
            "        }",
            "        return 0;",
            "    }",
            "",
        ]
        return lines

    def _proc_on_button(self) -> List[str]:
        lines = [
            "    // -------------------------------------------------------------------",
            "    // on_button - IDCMP_GADGETUP on a bool gadget (click completed over it).",
            "    // Return 1 to keep the form open, 0 to leave the event loop.",
            "    // -------------------------------------------------------------------",
            "    proc on_button(id: int) -> int {",
            "        var running: int = 1;",
            "",
        ]
        for c in self.buttons:
            lines += [
                f"        if (id == {c.id_const}) {{",
                self._user_block(
                    f"{c.name}.on_click", 12, f'button "{c.caption}" clicked'
                ),
                "        }",
                "",
            ]
        lines += ["        return running;", "    }", ""]
        return lines

    def _proc_on_string(self) -> List[str]:
        lines = [
            "    // -------------------------------------------------------------------",
            "    // on_string - IDCMP_GADGETUP on a string gadget: RETURN pressed or the",
            "    // gadget was tabbed away from. Only then is the buffer content stable.",
            "    // GuiGetEditText(id) returns the si_Buffer pointer.",
            "    // -------------------------------------------------------------------",
            "    proc on_string(id: int) -> int {",
            "        var running: int = 1;",
            "        var text_ptr: int;",
            "",
        ]
        for c in self.editboxes:
            lines += [
                f"        if (id == {c.id_const}) {{",
                f"            text_ptr = GuiGetEditText({c.id_const});",
                self._user_block(
                    f"{c.name}.on_change", 12, f'edit box "{c.name}" committed'
                ),
                "        }",
                "",
            ]
        lines += ["        return running;", "    }", ""]
        return lines

    def _proc_on_key(self) -> List[str]:
        return [
            "    // -------------------------------------------------------------------",
            "    // on_key - IDCMP_VANILLAKEY. 'code' is the translated ASCII value.",
            "    // -------------------------------------------------------------------",
            "    proc on_key(code: int) -> int {",
            "        var running: int = 1;",
            "",
            self._user_block("form.on_key", 8, "keyboard shortcuts go here"),
            "",
            "        return running;",
            "    }",
            "",
        ]

    def _proc_on_close(self) -> List[str]:
        return [
            "    // -------------------------------------------------------------------",
            "    // on_close - IDCMP_CLOSEWINDOW. Return 0 to exit, 1 to veto the close.",
            "    // -------------------------------------------------------------------",
            "    proc on_close() -> int {",
            "        var running: int = 0;",
            "",
            self._user_block("form.on_close", 8, "confirm-before-exit logic goes here"),
            "",
            "        return running;",
            "    }",
            "",
        ]

    # -- data --------------------------------------------------------------
    def _data_section(self) -> List[str]:
        lines = [
            "// =============================================================================",
            "// Read-only strings. Plain fast RAM: nothing here is DMA'd by the custom chips.",
            "// Every string must outlive the window - Intuition keeps the pointers.",
            "// =============================================================================",
            f"data {self.module}_strings:",
            f'    win_title.b = "{_has_str(self.m.window.caption)}", 0',
        ]
        for c in self.m.controls:
            if c.kind is ControlType.EDITBOX:
                continue
            lines.append(f'    {c.text_symbol}.b = "{_has_str(c.caption)}", 0')
        lines.append("")
        return lines

    def _bss_section(self) -> List[str]:
        if not self.editboxes:
            return []
        lines = [
            "// =============================================================================",
            "// String gadget storage. si_Buffer and si_UndoBuffer must be WRITABLE and each",
            "// at least maxlen bytes. Never share an undo buffer between gadgets.",
            "// =============================================================================",
            f"bss {self.module}_buffers:",
        ]
        for c in self.editboxes:
            lines.append(f"    {c.buffer_symbol}.b: {c.maxlen}")
            lines.append(f"    {c.undo_symbol}.b: {c.maxlen}")
        lines.append("")
        return lines

    # -- user code round-trip ---------------------------------------------
    def _user_block(
        self, key: str, indent: int, hint: str, seed: Optional[List[str]] = None
    ) -> str:
        pad = " " * indent
        body = self.user_code.get(key)
        if body is None:
            seed = seed if seed is not None else [f"// TODO: {hint}"]
            body = "\n".join(pad + line for line in seed)
        return f"{pad}// USER CODE BEGIN {key}\n{body.rstrip()}\n{pad}// USER CODE END {key}"


def _has_str(text: str) -> str:
    """HAS string literals have no escape sequences; sanitise instead."""
    return text.replace("\\", "").replace('"', "'")


def _portable_path(source: str) -> str:
    """Record the layout path CWD-relative with forward slashes, so the same
    project regenerates byte-identically on Windows and Linux."""
    if not source or source.startswith("<"):
        return source
    path = Path(source)
    try:
        path = path.resolve().relative_to(Path.cwd().resolve())
    except ValueError:
        pass
    return path.as_posix()


def extract_user_code(text: str) -> Dict[str, str]:
    """Pull every USER CODE BEGIN/END body out of a previously generated file."""
    return {m.group("key"): m.group("body").rstrip("\n") for m in _USER_BLOCK_RE.finditer(text)}


def render(
    manager: MetadataManager,
    module_name: str = "gui_form",
    meta_source: str = "<in-memory>",
    user_code: Optional[Dict[str, str]] = None,
) -> str:
    return HasEmitter(manager, module_name, meta_source, user_code).render()


def save(
    manager: MetadataManager,
    path: Path,
    meta_source: str = "<in-memory>",
    preserve_user_code: bool = True,
) -> Path:
    """Write the .has skeleton, carrying over any existing USER CODE bodies."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    user_code: Dict[str, str] = {}
    if preserve_user_code and path.exists():
        user_code = extract_user_code(path.read_text(encoding="utf-8"))
    text = render(manager, path.stem, meta_source, user_code)
    # BOM-less UTF-8: the HAS lexer rejects a BOM at line 1 col 1.
    path.write_text(text, encoding="utf-8", newline="\n")
    return path
