"""`.hasmeta` writer and reader.

The `.hasmeta` file is the contract between the visual designer and the 68000
pipeline: structured pseudo-code, not raw data. It is also the designer's own
project format, so the reader below is an exact inverse of the writer.

Layout (spec section 2.1):

    ; --- METADATA HEADER ---        DEFINE_WINDOW + BEGIN/END_GUI_LAYOUT
    ; --- EVENT HANDLER DEFINITIONS ---  HANDLE_ACTION mappings
    ; --- CONSTANTS/LAYOUT DATA ---  SECTION DATA CONSTANTS ... END_SECTION
"""

from __future__ import annotations

import re
import base64
from datetime import datetime
from pathlib import Path
from typing import Dict, List

from .model import (
    DEFAULT_IDCMP,
    Control,
    ControlType,
    MetadataManager,
    WindowSpec,
)

META_VERSION = "2.2"

_ATTR_RE = re.compile(
    r'(\w+)\s*=\s*(?:"([^"]*)"|(\$[0-9A-Fa-f]+|-?\d+|[A-Za-z_]\w*))'
)
_DEFINE_WINDOW_RE = re.compile(r"^\s*DEFINE_WINDOW\s+(.*)$")
_ADD_CONTROL_RE = re.compile(r"ADD_CONTROL\s*\((.*)\)\s*\}?\s*;?\s*$")


def _esc(text: str) -> str:
    """Metadata strings are double-quoted; strip the two characters that would
    break either the .hasmeta grammar or the emitted HAS string literal."""
    return text.replace('"', "'")


def _hex32(value: int) -> str:
    return f"${value & 0xFFFFFFFF:08X}"


def _parse_attrs(blob: str) -> Dict[str, str]:
    out: Dict[str, str] = {}
    for key, quoted, bare in _ATTR_RE.findall(blob):
        out[key.upper()] = quoted if bare == "" else bare
    return out


def _as_int(raw: str, default: int = 0) -> int:
    raw = raw.strip()
    if not raw:
        return default
    if raw.startswith("$"):
        return int(raw[1:], 16)
    try:
        return int(raw, 10)
    except ValueError:
        return default


# ---------------------------------------------------------------------------
# Writer
# ---------------------------------------------------------------------------


def render(manager: MetadataManager, source_name: str = "form") -> str:
    """Render the whole `.hasmeta` document as a string."""
    win = manager.window
    idcmp = DEFAULT_IDCMP
    flags = win.window_flags()
    lines: List[str] = []
    w = lines.append

    w("; =============================================================================")
    w(f"; {source_name}.hasmeta - GUI layout metadata for the HAS/68000 pipeline")
    w(f"; Generated by guicreator (format v{META_VERSION}) on "
      f"{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    w(";")
    w("; This file is pseudo-code, not a program. It is consumed by")
    w(";   python -m guicreator --export-has <this file> -o form.has")
    w("; and is also the designer's project format (round-trips exactly).")
    w("; =============================================================================")
    w("")

    w("; --- METADATA HEADER ---")
    w(
        f'DEFINE_WINDOW Caption="{_esc(win.caption)}" '
        f"WIDTH={win.width} HEIGHT={win.height} "
        f"LEFT={win.left} TOP={win.top} "
        f"FLAGS={_hex32(flags)} IDCMP={_hex32(idcmp)}"
    )
    w("; Simulates the intuition.library OpenWindow() resource allocation:")
    w(";   GuiInit() -> GuiBeginWindow(...) -> GuiAdd*(...) -> GuiShow()")
    w("")

    w("BEGIN_GUI_LAYOUT")
    if not manager.controls:
        w("    ; (empty layout)")
    for c in manager.controls:
        w(f"    {_control_line(c)}")
    w("END_GUI_LAYOUT")
    w("")

    w("; --- EVENT HANDLER DEFINITIONS ---")
    w("DEFINE_EVENT_HANDLERS START_MODULE")
    interactive = [c for c in manager.controls if c.kind.interactive]
    if not interactive:
        w("    ; (no interactive controls; the form only handles CLOSEWINDOW)")
    for c in interactive:
        if c.kind is ControlType.BUTTON:
            w(
                f"    HANDLE_ACTION(ID: {c.action_id}, ACTION: BUTTON_CLICK): "
                f"CALL_FUNCTION(amiga_button_action_{c.action_id});"
            )
        elif c.kind is ControlType.EDITBOX:
            w(
                f"    HANDLE_ACTION(ID: {c.action_id}, ACTION: EDITBOX_CHANGE): "
                f"PROCESS_INPUT(memory_offset={c.buffer_symbol}, "
                f"max_chars={c.maxlen});"
            )
        elif c.kind is ControlType.CHECKBOX:
            w(f"    HANDLE_ACTION(ID: {c.action_id}, ACTION: CHECKBOX_CHANGE): CALL_FUNCTION(amiga_checkbox_action_{c.action_id});")
        elif c.kind is ControlType.LIST:
            w(f"    HANDLE_ACTION(ID: {c.action_id}, ACTION: LIST_SELECT): CALL_FUNCTION(amiga_list_action_{c.action_id});")
    w("    HANDLE_ACTION(ID: 0, ACTION: WINDOW_CLOSE): CALL_FUNCTION(amiga_window_close);")
    w("END_EVENT_HANDLERS")
    w("")

    w("; --- CONSTANTS/LAYOUT DATA (For Assembler Consumption) ---")
    w("SECTION DATA CONSTANTS")
    w(f'    WINDOW_CAPTION        EQU "{_esc(win.caption)}"')
    w(f"    WINDOW_WIDTH          EQU {win.width}")
    w(f"    WINDOW_HEIGHT         EQU {win.height}")
    w(f"    WINDOW_LEFT           EQU {win.left}")
    w(f"    WINDOW_TOP            EQU {win.top}")
    w(f"    WINDOW_FLAGS          EQU {_hex32(flags)}")
    w(f"    WINDOW_IDCMP          EQU {_hex32(idcmp)}")
    w("    CONTROL_TYPE_LABEL    EQU 0")
    w("    CONTROL_TYPE_BUTTON   EQU 1")
    w("    CONTROL_TYPE_EDITBOX  EQU 2")
    w("    CONTROL_TYPE_CHECKBOX EQU 3")
    w("    CONTROL_TYPE_LIST     EQU 4")
    w("    CONTROL_TYPE_BITMAP   EQU 5")
    w(f"    CONTROL_COUNT         EQU {len(manager.controls)}")
    w("")
    for c in manager.controls:
        w(f"    {c.id_const:<21} EQU {c.action_id}")
    for c in manager.by_kind(ControlType.EDITBOX):
        w(f"    {c.maxlen_const:<21} EQU {c.maxlen}")
    w("END_SECTION")
    w("")
    return "\n".join(lines) + "\n"


def _control_line(c: Control) -> str:
    parts = [
        f"TYPE={c.kind.value}",
        f"ID={c.action_id}",
        f"X={c.x}",
        f"Y={c.y}",
        f"W={c.w}",
        f"H={c.h}",
        f'NAME="{c.name}"',
    ]
    if c.kind is ControlType.LABEL:
        parts.append(f'TEXT="{_esc(c.caption)}"')
    elif c.kind is ControlType.BUTTON:
        parts.append(f'CAPT="{_esc(c.caption)}"')
    elif c.kind is ControlType.EDITBOX:
        parts.append(f'ITEXT="{_esc(c.caption)}"')
        parts.append(f"MAXLEN={c.maxlen}")
    elif c.kind is ControlType.CHECKBOX:
        parts.append(f'CAPT="{_esc(c.caption)}"')
        parts.append(f"CHECKED={int(c.checked)}")
    elif c.kind is ControlType.LIST:
        payload = base64.b64encode("\0".join(c.items).encode("utf-8")).decode("ascii")
        parts.append(f'ITEMS64="{payload}"')
        parts.append(f"SELECTED={c.selected}")
    else:
        parts.append(f'ASSET="{_esc(c.asset_path)}"')
        parts.append(f"COLORS={c.bitmap_colors}")
    return "{CALL_HAS_CMD: ADD_CONTROL(" + ", ".join(parts) + ")}"


def save(manager: MetadataManager, path: Path, source_name: str | None = None) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    text = render(manager, source_name or path.stem)
    # BOM-less UTF-8: the HAS lexer and vasm both reject a BOM.
    path.write_text(text, encoding="utf-8", newline="\n")
    return path


# ---------------------------------------------------------------------------
# Reader
# ---------------------------------------------------------------------------


def loads(text: str) -> MetadataManager:
    """Rebuild a MetadataManager from `.hasmeta` source."""
    manager = MetadataManager()
    in_layout = False

    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith(";"):
            continue

        header = _DEFINE_WINDOW_RE.match(line)
        if header:
            _apply_window(manager.window, _parse_attrs(header.group(1)))
            continue

        if line.startswith("BEGIN_GUI_LAYOUT"):
            in_layout = True
            continue
        if line.startswith("END_GUI_LAYOUT"):
            in_layout = False
            continue

        if in_layout:
            body = _ADD_CONTROL_RE.search(line)
            if body:
                _apply_control(manager, _parse_attrs(body.group(1)))

    return manager


def load(path: Path) -> MetadataManager:
    return loads(Path(path).read_text(encoding="utf-8"))


def _apply_window(win: WindowSpec, attrs: Dict[str, str]) -> None:
    win.caption = attrs.get("CAPTION", win.caption)
    win.width = _as_int(attrs.get("WIDTH", ""), win.width)
    win.height = _as_int(attrs.get("HEIGHT", ""), win.height)
    win.left = _as_int(attrs.get("LEFT", ""), win.left)
    win.top = _as_int(attrs.get("TOP", ""), win.top)
    if "FLAGS" in attrs:
        flags = _as_int(attrs["FLAGS"], 0)
        win.sizeable = bool(flags & 0x00000001)
        win.dragbar = bool(flags & 0x00000002)
        win.depth_gadget = bool(flags & 0x00000004)
        win.close_gadget = bool(flags & 0x00000008)
        win.activate = bool(flags & 0x00001000)


def _apply_control(manager: MetadataManager, attrs: Dict[str, str]) -> None:
    try:
        kind = ControlType(attrs.get("TYPE", "").upper())
    except ValueError:
        return
    caption = attrs.get("TEXT") or attrs.get("CAPT") or attrs.get("ITEXT") or ""
    manager.add(
        kind=kind,
        x=_as_int(attrs.get("X", ""), 0),
        y=_as_int(attrs.get("Y", ""), 0),
        w=_as_int(attrs.get("W", ""), 0) or None,
        h=_as_int(attrs.get("H", ""), 0) or None,
        caption=caption,
        name=attrs.get("NAME") or None,
        maxlen=_as_int(attrs.get("MAXLEN", ""), 32),
        checked=bool(_as_int(attrs.get("CHECKED", ""), 0)),
        items=_decode_items(attrs),
        selected=_as_int(attrs.get("SELECTED", ""), 0),
        asset_path=attrs.get("ASSET", ""),
        bitmap_colors=_as_int(attrs.get("COLORS", ""), 2),
        action_id=_as_int(attrs.get("ID", ""), 0) or None,
    )


def _decode_items(attrs: Dict[str, str]) -> List[str]:
    payload = attrs.get("ITEMS64", "")
    if payload:
        try:
            return base64.b64decode(payload.encode("ascii")).decode("utf-8").split("\0")
        except (UnicodeDecodeError, ValueError):
            return []
    return [item for item in attrs.get("ITEMS", "").split("|") if item]
