"""pythonami `.py` skeleton emitter for guicreator layouts.

Turns a MetadataManager into a Python68K-compatible script that talks to the
Layer 1 gui_intuition LoadSeg plugin (docs/GUI_PYTHONAMI_API.md).

Regeneration is non-destructive: bodies between
`# USER CODE BEGIN <key>` and `# USER CODE END <key>` are preserved.
"""

from __future__ import annotations

import re
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional

from .model import (
    DEFAULT_IDCMP,
    Control,
    ControlType,
    MetadataManager,
)

_USER_BLOCK_RE = re.compile(
    r"#\s*USER CODE BEGIN\s+(?P<key>\S+)\s*\n(?P<body>.*?)^[ \t]*#\s*USER CODE END\s+(?P=key)",
    re.DOTALL | re.MULTILINE,
)

_PLUGIN_PATH = "PROGDIR:ext/gui_intuition/gui_intuition.py68k"


class PyEmitter:
    """Renders a pythonami source file for one designed form."""

    def __init__(
        self,
        manager: MetadataManager,
        module_name: str = "gui_form",
        meta_source: str = "<in-memory>",
        user_code: Optional[Dict[str, str]] = None,
    ) -> None:
        self.m = manager
        self.module = re.sub(r"\W", "_", module_name) or "gui_form"
        self.meta_source = _portable_path(meta_source)
        self.user_code = user_code or {}
        self.buttons = manager.by_kind(ControlType.BUTTON)
        self.editboxes = manager.by_kind(ControlType.EDITBOX)
        self.labels = manager.by_kind(ControlType.LABEL)
        self.checkboxes = manager.by_kind(ControlType.CHECKBOX)
        self.lists = manager.by_kind(ControlType.LIST)
        self.bitmaps = manager.by_kind(ControlType.BITMAP)

    def render(self) -> str:
        out: List[str] = []
        out += self._header()
        out += self._constants()
        out += self._helpers()
        out += self._main()
        out += self._event_loop()
        if self.buttons:
            out += self._on_button()
        if self.editboxes:
            out += self._on_string()
        if self.checkboxes:
            out += self._on_checkbox()
        if self.lists:
            out += self._on_list()
        out += self._on_key()
        out += self._on_close()
        out += [
            "",
            'if __name__ == "__main__":',
            "    exit(main())",
            "",
        ]
        return "\n".join(out).rstrip() + "\n"

    def _header(self) -> List[str]:
        win = self.m.window
        return [
            "# =============================================================================",
            f"# {self.module}.py - GENERATED BY guicreator",
            f"# Layout source : {self.meta_source}",
            f"# Generated     : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            "#",
            "# pythonami (Python68K) Intuition form. Calls Layer 1 of",
            "# docs/GUI_PYTHONAMI_API.md via load_library.",
            "#",
            "# Only the bodies between USER CODE BEGIN/END markers survive regeneration.",
            "#",
            "# Amiga:",
            f"#   pythonami {self.module}.py",
            f"#   (requires {_PLUGIN_PATH})",
            "# =============================================================================",
            "",
            f'# Window: "{win.caption}"  {win.width}x{win.height} at ({win.left},{win.top})',
            "",
        ]

    def _constants(self) -> List[str]:
        win = self.m.window
        lines = [
            "# ---- window geometry ----",
            f"WIN_X = {win.left}",
            f"WIN_Y = {win.top}",
            f"WIN_W = {win.width}",
            f"WIN_H = {win.height}",
            f'WIN_TITLE = "{_py_str(win.caption)}"',
            "",
            "# ---- IDCMP mask and window flags ----",
            f"FORM_IDCMP = {DEFAULT_IDCMP}",
            f"FORM_FLAGS = {win.window_flags()}",
            "",
            "# ---- event classes (must match HAS / GUI_PYTHONAMI_API.md) ----",
            "GUI_EVT_NONE = 0",
            "GUI_EVT_CLOSE = 1",
            "GUI_EVT_BUTTON = 2",
            "GUI_EVT_PRESS = 3",
            "GUI_EVT_STRING = 4",
            "GUI_EVT_KEY = 5",
            "GUI_EVT_MOUSE = 6",
            "GUI_EVT_REFRESH = 7",
            "GUI_EVT_CHECKBOX = 8",
            "GUI_EVT_LIST = 9",
            "",
            "# ---- widget ActionIDs ----",
        ]
        if self.m.controls:
            width = max(len(c.id_const) for c in self.m.controls)
            for c in self.m.controls:
                lines.append(f"{c.id_const:<{width}} = {c.action_id}")
        else:
            lines.append("# (no controls placed)")
        if self.editboxes:
            lines.append("")
            lines.append("# ---- string gadget buffer sizes (maxlen includes NUL) ----")
            width = max(len(c.maxlen_const) for c in self.editboxes)
            for c in self.editboxes:
                lines.append(f"{c.maxlen_const:<{width}} = {c.maxlen}")
        for c in self.lists:
            items = ", ".join(f'"{_py_str(item)}"' for item in c.items)
            lines.append(f"{c.name}_ITEMS = [{items}]")
        lines.append("")
        lines.append(f'GUI_PLUGIN = "{_PLUGIN_PATH}"')
        lines.append("")
        return lines

    def _helpers(self) -> List[str]:
        return [
            self._user_block("form.externs", 0, "", seed=[
                "import sys",
                'sys.path.append("lib")',
                "import gui_dialog",
            ]),
            "",
        ]

    def _main(self) -> List[str]:
        lines = [
            "def main():",
            "    gui = load_library(GUI_PLUGIN)",
            "    status = gui.init()",
            "    if status != 0:",
            "        return -1",
            "",
            "    status = gui.begin_window("
            "WIN_TITLE, WIN_X, WIN_Y, WIN_W, WIN_H, FORM_IDCMP, FORM_FLAGS)",
            "    if status != 0:",
            "        gui.shutdown()",
            "        return -1",
            "",
        ]
        for c in self.m.controls:
            lines.append("    " + self._add_call(c))
        lines += [
            "",
            "    win = gui.show()",
            "    if win == 0:",
            "        gui.shutdown()",
            "        return -1",
            "    if win == -1:",
            "        gui.shutdown()",
            "        return -1",
            "",
            self._user_block(
                "main.after_show", 4, "custom initialisation once the window is up"
            ),
            "",
            "    event_loop(gui)",
            "",
            "    gui.close_window()",
            "    gui.shutdown()",
            "    return 0",
            "",
        ]
        return lines

    def _add_call(self, c: Control) -> str:
        if c.kind is ControlType.LABEL:
            return (
                f'gui.add_label({c.id_const}, {c.x}, {c.y}, "{_py_str(c.caption)}")'
            )
        if c.kind is ControlType.BUTTON:
            return (
                f"gui.add_button({c.id_const}, {c.x}, {c.y}, {c.w}, {c.h}, "
                f'"{_py_str(c.caption)}")'
            )
        if c.kind is ControlType.EDITBOX:
            return (
                f"gui.add_editbox({c.id_const}, {c.x}, {c.y}, {c.w}, {c.h}, "
                f'"{_py_str(c.caption)}", {c.maxlen_const})'
            )
        if c.kind is ControlType.CHECKBOX:
            return (
                f"gui.add_checkbox({c.id_const}, {c.x}, {c.y}, {c.w}, {c.h}, "
                f'"{_py_str(c.caption)}", {int(c.checked)})'
            )
        if c.kind is ControlType.LIST:
            return (
                f"gui.add_list({c.id_const}, {c.x}, {c.y}, {c.w}, {c.h}, "
                f"{c.name}_ITEMS, {c.selected})"
            )
        path = _py_str(c.asset_path)
        return (
            f"gui.add_bitmap({c.id_const}, {c.x}, {c.y}, {c.w}, {c.h}, "
            f'"{path}")'
        )

    def _event_loop(self) -> List[str]:
        lines = [
            "def event_loop(gui):",
            "    running = 1",
            "    while running != 0:",
            "        evt = gui.wait_event()",
            "        eid = gui.get_event_id()",
            "",
            "        if evt == GUI_EVT_CLOSE:",
            "            running = on_close(gui)",
        ]
        if self.buttons:
            lines += [
                "        if evt == GUI_EVT_BUTTON:",
                "            running = on_button(gui, eid)",
            ]
        if self.editboxes:
            lines += [
                "        if evt == GUI_EVT_STRING:",
                "            running = on_string(gui, eid)",
            ]
        if self.checkboxes:
            lines += [
                "        if evt == GUI_EVT_CHECKBOX:",
                "            running = on_checkbox(gui, eid)",
            ]
        if self.lists:
            lines += [
                "        if evt == GUI_EVT_LIST:",
                "            running = on_list(gui, eid)",
            ]
        lines += [
            "        if evt == GUI_EVT_KEY:",
            "            running = on_key(gui, gui.get_event_code())",
            "",
        ]
        return lines

    def _on_button(self) -> List[str]:
        lines = [
            "def on_button(gui, eid):",
            "    running = 1",
            "",
        ]
        for c in self.buttons:
            lines += [
                f"    if eid == {c.id_const}:",
                "        pass",
                self._user_block(
                    f"{c.name}.on_click", 8, f'button "{c.caption}" clicked'
                ),
                "",
            ]
        lines += ["    return running", ""]
        return lines

    def _on_string(self) -> List[str]:
        lines = [
            "def on_string(gui, eid):",
            "    running = 1",
            "",
        ]
        for c in self.editboxes:
            lines += [
                f"    if eid == {c.id_const}:",
                f"        text = gui.get_edit_text({c.id_const})",
                self._user_block(
                    f"{c.name}.on_change", 8, f'edit box "{c.name}" committed'
                ),
                "",
            ]
        lines += ["    return running", ""]
        return lines

    def _on_checkbox(self) -> List[str]:
        lines = [
            "def on_checkbox(gui, eid):",
            "    running = 1",
            "",
        ]
        for c in self.checkboxes:
            lines += [
                f"    if eid == {c.id_const}:",
                f"        checked = gui.get_checkbox({c.id_const})",
                self._user_block(
                    f"{c.name}.on_change", 8, f'checkbox "{c.caption}" changed'
                ),
                "",
            ]
        lines += ["    return running", ""]
        return lines

    def _on_list(self) -> List[str]:
        lines = [
            "def on_list(gui, eid):",
            "    running = 1",
            "",
        ]
        for c in self.lists:
            lines += [
                f"    if eid == {c.id_const}:",
                f"        selected = gui.get_list_selected({c.id_const})",
                self._user_block(
                    f"{c.name}.on_select", 8, f'list "{c.name}" selected a row'
                ),
                "",
            ]
        lines += ["    return running", ""]
        return lines

    def _on_key(self) -> List[str]:
        return [
            "def on_key(gui, code):",
            "    running = 1",
            "",
            self._user_block("form.on_key", 4, "keyboard shortcuts go here"),
            "",
            "    return running",
            "",
        ]

    def _on_close(self) -> List[str]:
        return [
            "def on_close(gui):",
            "    running = 0",
            "",
            self._user_block("form.on_close", 4, "confirm-before-exit logic goes here"),
            "",
            "    return running",
            "",
        ]

    def _user_block(
        self, key: str, indent: int, hint: str, seed: Optional[List[str]] = None
    ) -> str:
        pad = " " * indent
        body = self.user_code.get(key)
        if body is None:
            # Keep a real statement; comments alone are not a suite in pythonami.
            seed = seed if seed is not None else [f"# TODO: {hint}"]
            body = "\n".join(pad + line for line in seed)
        return f"{pad}# USER CODE BEGIN {key}\n{body.rstrip()}\n{pad}# USER CODE END {key}"


def _py_str(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"')


def _portable_path(source: str) -> str:
    if not source or source.startswith("<"):
        return source
    path = Path(source)
    try:
        path = path.resolve().relative_to(Path.cwd().resolve())
    except ValueError:
        pass
    return path.as_posix()


def extract_user_code(text: str) -> Dict[str, str]:
    return {m.group("key"): m.group("body").rstrip("\n") for m in _USER_BLOCK_RE.finditer(text)}


def render(
    manager: MetadataManager,
    module_name: str = "gui_form",
    meta_source: str = "<in-memory>",
    user_code: Optional[Dict[str, str]] = None,
) -> str:
    return PyEmitter(manager, module_name, meta_source, user_code).render()


def save(
    manager: MetadataManager,
    path: Path,
    meta_source: str = "<in-memory>",
    preserve_user_code: bool = True,
) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    user_code: Dict[str, str] = {}
    if preserve_user_code and path.exists():
        user_code = extract_user_code(path.read_text(encoding="utf-8"))
    text = render(manager, path.stem, meta_source, user_code)
    path.write_text(text, encoding="utf-8", newline="\n")
    return path
